/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan4;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHGenParameterSpec;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author Hieu Pham
 */
public class formAlice extends javax.swing.JFrame {

    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;

    /**
     * Creates new form formAlice
     */
    public formAlice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldKhoaAlice = new javax.swing.JTextField();
        jTextFieldKhoaBoB = new javax.swing.JTextField();
        jTextFieldKhoaKAB = new javax.swing.JTextField();
        jTextFieldMaHoaKAB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonTaoKhoa = new javax.swing.JButton();
        jButtonHienThiKB = new javax.swing.JButton();
        jButtonKhoaChung = new javax.swing.JButton();
        jButtonMaHoaKAB = new javax.swing.JButton();
        jButtonMaHoaGiaiMa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Khóa Alice");

        jLabel2.setText("Khóa BoB");

        jLabel3.setText("Khóa KAB");

        jLabel4.setText("Mã hóa KAB");

        jLabel5.setText("Alice");

        jButtonTaoKhoa.setText("Tạo khóa A");
        jButtonTaoKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoKhoaActionPerformed(evt);
            }
        });

        jButtonHienThiKB.setText("Hiển thị KB");
        jButtonHienThiKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHienThiKBActionPerformed(evt);
            }
        });

        jButtonKhoaChung.setText("Khóa chung");
        jButtonKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKhoaChungActionPerformed(evt);
            }
        });

        jButtonMaHoaKAB.setText("Mã hóa KAB");
        jButtonMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaHoaKABActionPerformed(evt);
            }
        });

        jButtonMaHoaGiaiMa.setText("Mã hóa / Giải mã");
        jButtonMaHoaGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaHoaGiaiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMaHoaGiaiMa)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonKhoaChung)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldKhoaAlice)
                                        .addComponent(jTextFieldKhoaBoB)
                                        .addComponent(jTextFieldKhoaKAB)
                                        .addComponent(jTextFieldMaHoaKAB, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonMaHoaKAB)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButtonTaoKhoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                            .addComponent(jButtonHienThiKB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKhoaAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTaoKhoa))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldKhoaBoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHienThiKB))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldKhoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKhoaChung))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMaHoaKAB))
                .addGap(47, 47, 47)
                .addComponent(jButtonMaHoaGiaiMa)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTaoKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoKhoaActionPerformed
        // TODO add your handling code here:
        try {
            AlgorithmParameterGenerator paramGen = AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            DHParameterSpec dhSkipParamSpec = (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);

            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair();

            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());

            byte[] alicePubKeyEnc = aliceKpair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();
            jTextFieldKhoaAlice.setText(alicePubKeyEnc.toString());
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonTaoKhoaActionPerformed

    private void jButtonHienThiKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHienThiKBActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\B.pub");
            byte[] bkeyP = new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            jTextFieldKhoaBoB.setText(bkeyP.toString());
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonHienThiKBActionPerformed

    private void jButtonKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKhoaChungActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\B.pub");
            byte[] bobPubKeyEnc = new byte[fis.available()];
            fis.read(bobPubKeyEnc);
            fis.close();

            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(bobPubKeyEnc);
            bobPubKey = aliceKeyFac.generatePublic(x509KeySpec);
            System.out.println("Excuting PHASE1 of key argreement");
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] aliceSharedSecret = aliceKeyAgree.generateSecret();

            System.out.println("Khoa chung: secret (DEBUG ONLY)" + CryptoUtil.toHexString(aliceSharedSecret));
            jTextFieldKhoaKAB.setText(CryptoUtil.toHexString(aliceSharedSecret));
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonKhoaChungActionPerformed

    private void jButtonMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaHoaKABActionPerformed
        try {
            // TODO add your handling code here:
            aliceKeyAgree.doPhase(bobPubKey, true);
            aliceDesKey = aliceKeyAgree.generateSecret("DES");
            jTextFieldMaHoaKAB.setText(aliceDesKey.toString());
            BufferedWriter bw = null;
            String fileName = "H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\KhoaA.txt";
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(aliceDesKey.toString());
            bw.close();
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_jButtonMaHoaKABActionPerformed

    private void jButtonMaHoaGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaHoaGiaiMaActionPerformed
        // TODO add your handling code here:
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_jButtonMaHoaGiaiMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAlice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAlice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHienThiKB;
    private javax.swing.JButton jButtonKhoaChung;
    private javax.swing.JButton jButtonMaHoaGiaiMa;
    private javax.swing.JButton jButtonMaHoaKAB;
    private javax.swing.JButton jButtonTaoKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldKhoaAlice;
    private javax.swing.JTextField jTextFieldKhoaBoB;
    private javax.swing.JTextField jTextFieldKhoaKAB;
    private javax.swing.JTextField jTextFieldMaHoaKAB;
    // End of variables declaration//GEN-END:variables
}
