/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan4;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHGenParameterSpec;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author Hieu Pham
 */
public class formBob extends javax.swing.JFrame {

    KeyAgreement bobKeyAgree;
    PublicKey alicePubKey;
    SecretKey bobDesKey;
    Cipher bobCipher;

    /**
     * Creates new form formBob
     */
    public formBob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldKhoaB = new javax.swing.JTextField();
        jTextFieldKhoaA = new javax.swing.JTextField();
        jTextFieldKhoaAB = new javax.swing.JTextField();
        jTextFieldMaHoaKAB = new javax.swing.JTextField();
        jButtonTaoKhoaB = new javax.swing.JButton();
        jButtonHienThiKhoaA = new javax.swing.JButton();
        jButtonKhoaChung = new javax.swing.JButton();
        jButtonMaHoaKAB = new javax.swing.JButton();
        jButtonMaHoaGiaiMa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bob");

        jLabel2.setText("Khóa Bob");

        jLabel3.setText("Khóa Alice");

        jLabel4.setText("Khóa KAB");

        jLabel5.setText("Mã hóa KAB");

        jTextFieldKhoaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKhoaABActionPerformed(evt);
            }
        });

        jButtonTaoKhoaB.setText("Tạo khóa B");
        jButtonTaoKhoaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoKhoaBActionPerformed(evt);
            }
        });

        jButtonHienThiKhoaA.setText("Hiển thị KA");
        jButtonHienThiKhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHienThiKhoaAActionPerformed(evt);
            }
        });

        jButtonKhoaChung.setText("Khóa chung");
        jButtonKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKhoaChungActionPerformed(evt);
            }
        });

        jButtonMaHoaKAB.setText("Mã hóa KAB");
        jButtonMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaHoaKABActionPerformed(evt);
            }
        });

        jButtonMaHoaGiaiMa.setText("Mã hóa / Giải mã");
        jButtonMaHoaGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaHoaGiaiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButtonMaHoaGiaiMa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jTextFieldMaHoaKAB)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldKhoaAB, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(jTextFieldKhoaA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldKhoaB, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTaoKhoaB)
                    .addComponent(jButtonHienThiKhoaA)
                    .addComponent(jButtonKhoaChung)
                    .addComponent(jButtonMaHoaKAB))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldKhoaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTaoKhoaB))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldKhoaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHienThiKhoaA))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldKhoaAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKhoaChung))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMaHoaKAB))
                .addGap(30, 30, 30)
                .addComponent(jButtonMaHoaGiaiMa)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHienThiKhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHienThiKhoaAActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\B.pub");
            byte[] akeyP = new byte[fis.available()];
            fis.read(akeyP);
            fis.close();
            jTextFieldKhoaA.setText(akeyP.toString());
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonHienThiKhoaAActionPerformed

    private void jButtonTaoKhoaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoKhoaBActionPerformed
        // TODO add your handling code here:
        try {
            boolean read = false;
            while (!read) {
                try {
                    FileInputStream fis = new FileInputStream("H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\A.pub");
                    fis.close();
                    read = true;
                } catch (Exception e) {
                }
            }
            FileInputStream fis = new FileInputStream("H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\A.pub");
            byte[] alicePubKeyEnc = new byte[fis.available()];
            fis.read(alicePubKeyEnc);
            fis.close();

            KeyFactory bobKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(alicePubKeyEnc);
            alicePubKey = bobKeyFac.generatePublic(x509KeySpec);
            DHParameterSpec dhParamSpec = ((DHPublicKey) alicePubKey).getParams();
            System.out.println("Generate DH keypair...");
            KeyPairGenerator bobKpairGen = KeyPairGenerator.getInstance("DH");
            bobKpairGen.initialize(dhParamSpec);
            KeyPair bobKpair = bobKpairGen.generateKeyPair();
            System.out.println("Initializing KeyAgreement engine...");
            bobKeyAgree = KeyAgreement.getInstance("DH");
            bobKeyAgree.init(bobKpair.getPrivate());
            byte[] bobPubKeyEnc = bobKpair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\B.pub");
            fos.write(bobPubKeyEnc);
            fos.close();
            jTextFieldKhoaB.setText(bobPubKeyEnc.toString());
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonTaoKhoaBActionPerformed

    private void jButtonKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKhoaChungActionPerformed
        // TODO add your handling code here:
        try {
            bobKeyAgree.doPhase(bobDesKey, true);
            byte[] bobShareSecret = bobKeyAgree.generateSecret();
            System.out.println("Khoa chung: secret (DEBUG ONLY)" + CryptoUtil.toHexString(bobShareSecret));
            jTextFieldKhoaAB.setText(CryptoUtil.toHexString(bobShareSecret));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButtonKhoaChungActionPerformed

    private void jButtonMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaHoaKABActionPerformed
        try {
            // TODO add your handling code here:
            bobKeyAgree.doPhase(alicePubKey, true);
            bobDesKey = bobKeyAgree.generateSecret("DES");
            jTextFieldMaHoaKAB.setText(bobDesKey.toString());
            BufferedWriter bw = null;
            String fileName = "H:\\BaoMatThongTin\\TH_BMTT\\Tuan4\\Khoab.txt";
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(bobDesKey.toString());
            bw.close();
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_jButtonMaHoaKABActionPerformed

    private void jButtonMaHoaGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaHoaGiaiMaActionPerformed
        // TODO add your handling code here:
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_jButtonMaHoaGiaiMaActionPerformed

    private void jTextFieldKhoaABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKhoaABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKhoaABActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formBob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formBob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHienThiKhoaA;
    private javax.swing.JButton jButtonKhoaChung;
    private javax.swing.JButton jButtonMaHoaGiaiMa;
    private javax.swing.JButton jButtonMaHoaKAB;
    private javax.swing.JButton jButtonTaoKhoaB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldKhoaA;
    private javax.swing.JTextField jTextFieldKhoaAB;
    private javax.swing.JTextField jTextFieldKhoaB;
    private javax.swing.JTextField jTextFieldMaHoaKAB;
    // End of variables declaration//GEN-END:variables
}
